name: docx_viewer
description: A Flutter package which allows you to view Docx/Doc document format for Android.
version: 0.2.2
homepage: https://github.com/mechimavericks/docx_viewer
repository: https://github.com/mechimavericks/docx_viewer
documentation: https://pub.dev/packages/docx_viewer
environment:
  sdk: ^3.5.4
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  archive: any
  xml: any
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

        
